Repository lanit-office-map/OfficeMap, pull requests merged in 2020-04, with the labels that each got.

#1 User service for the solution
  OfficeMapApi/OfficeMapApi.sln
  OfficeMapApi/UserService/UserService/Database/Entities/DbEmployee.cs
  OfficeMapApi/UserService/UserService/Database/Entities/DbUser.cs
  OfficeMapApi/UserService/UserService/Database/UserServiceDBContext.cs
  OfficeMapApi/UserService/UserService/Migrations/20200324191148_InitialCreate.Designer.cs
  OfficeMapApi/UserService/UserService/Migrations/20200324191148_InitialCreate.cs
  OfficeMapApi/UserService/UserService/Migrations/UserServiceDBContextModelSnapshot.cs
  OfficeMapApi/UserService/UserService/Models/User.cs
  OfficeMapApi/UserService/UserService/Program.cs
  OfficeMapApi/UserService/UserService/Properties/launchSettings.json
  OfficeMapApi/UserService/UserService/Startup.cs
  OfficeMapApi/UserService/UserService/UserService.csproj
  OfficeMapApi/UserService/UserService/appsettings.Development.json
  OfficeMapApi/UserService/UserService/appsettings.json
Labels: backend, math-mech

#7 UserService: Models
  OfficeMapApi/OfficeMapApi.sln
  OfficeMapApi/UserService/UserService/Models/Employee.cs
  OfficeMapApi/UserService/UserService/Models/User.cs
Labels: backend, math-mech

#16 UserService: db correction
  OfficeMapApi/UserService/UserService/Database/UserServiceDBContext.cs
Labels: backend

#15 OfficeService: Models
  OfficeMapApi/OfficeMapApi.sln
  OfficeMapApi/OfficeService/OfficeService/Models/Office.cs
  OfficeMapApi/OfficeService/OfficeService/Models/Space.cs
  OfficeMapApi/OfficeService/OfficeService/OfficeService.csproj
  OfficeMapApi/OfficeService/OfficeService/Program.cs
  OfficeMapApi/OfficeService/OfficeService/Properties/launchSettings.json
  OfficeMapApi/OfficeService/OfficeService/Startup.cs
  OfficeMapApi/OfficeService/OfficeService/appsettings.Development.json
  OfficeMapApi/OfficeService/OfficeService/appsettings.json
Labels: backend

#19 OfficeService. Repositories
  OfficeMapApi/OfficeService/OfficeService/Interfaces/ICreate.cs
  OfficeMapApi/OfficeService/OfficeService/Interfaces/IDelete.cs
  OfficeMapApi/OfficeService/OfficeService/Interfaces/IFind.cs
  OfficeMapApi/OfficeService/OfficeService/Interfaces/IGet.cs
  OfficeMapApi/OfficeService/OfficeService/Interfaces/IUpdate.cs
  OfficeMapApi/OfficeService/OfficeService/Models/Office.cs
  OfficeMapApi/OfficeService/OfficeService/Models/Space.cs
  OfficeMapApi/OfficeService/OfficeService/Repository/Filters/OfficeFilter.cs
  OfficeMapApi/OfficeService/OfficeService/Repository/Interfaces/IOfficeRepository.cs
  OfficeMapApi/OfficeService/OfficeService/Repository/OfficeRepository.cs
Labels: GitGud, backend

#22 UserService: UserController
  OfficeMapApi/UserService/UserService/Controllers/AccountController.cs
  OfficeMapApi/UserService/UserService/Controllers/UserController.cs
  OfficeMapApi/UserService/UserService/Database/Entities/DbEmployee.cs
  OfficeMapApi/UserService/UserService/Database/UserServiceDBContext.cs
  OfficeMapApi/UserService/UserService/Models/Employee.cs
  OfficeMapApi/UserService/UserService/Models/LoginUserModel.cs
  OfficeMapApi/UserService/UserService/Models/RegisterUserModel.cs
  OfficeMapApi/UserService/UserService/Models/User.cs
  OfficeMapApi/UserService/UserService/Startup.cs
  OfficeMapApi/UserService/UserService/UserModelsProfile.cs
  OfficeMapApi/UserService/UserService/UserService.csproj
Labels: backend, math-mech

#33 SpaceService: SpaceType Requests
  OfficeMapApi/SpaceService/SpaceService/Controllers/SpaceTypeController.cs
  OfficeMapApi/SpaceService/SpaceService/Interfaces/ICreate.cs
  OfficeMapApi/SpaceService/SpaceService/Interfaces/IDelete.cs
  OfficeMapApi/SpaceService/SpaceService/Interfaces/IGet.cs
  OfficeMapApi/SpaceService/SpaceService/Interfaces/IUpdate.cs
  OfficeMapApi/SpaceService/SpaceService/Repository/Filters/SpaceFilter.cs
  OfficeMapApi/SpaceService/SpaceService/Repository/Filters/SpaceTypeFilter.cs
  OfficeMapApi/SpaceService/SpaceService/Repository/Interfaces/ISpaceTypeRepository.cs
  OfficeMapApi/SpaceService/SpaceService/Repository/SpaceTypeRepository.cs
  OfficeMapApi/SpaceService/SpaceService/Services/Interfaces/ISpaceTypeService.cs
  OfficeMapApi/SpaceService/SpaceService/Services/SpaceTypeService.cs
Labels: backend

#31 MapService: add database
  OfficeMapApi/MapService/Database/Entities/DbMapFiles.cs
  OfficeMapApi/MapService/Database/MapServiceDbContext.cs
  OfficeMapApi/MapService/Interfaces/ICreate.cs
  OfficeMapApi/MapService/Interfaces/IDelete.cs
  OfficeMapApi/MapService/Interfaces/IFind.cs
  OfficeMapApi/MapService/Interfaces/IGet.cs
  OfficeMapApi/MapService/Interfaces/IUpdate.cs
  OfficeMapApi/MapService/MapService.csproj
  OfficeMapApi/MapService/Mappers/MapModelsProfile.cs
  OfficeMapApi/MapService/Migrations/20200425111335_InitialCreate.Designer.cs
  OfficeMapApi/MapService/Migrations/20200425111335_InitialCreate.cs
  OfficeMapApi/MapService/Migrations/MapServiceDbContextModelSnapshot.cs
  OfficeMapApi/MapService/Models/MapFiles.cs
  OfficeMapApi/MapService/Repository/Filters/MapFilesFilter.cs
  OfficeMapApi/MapService/Repository/Interfaces/IMapFilesRepository.cs
  OfficeMapApi/MapService/Repository/MapFilesRepository.cs
  OfficeMapApi/MapService/Services/Interfaces/IMapService.cs
  OfficeMapApi/MapService/Services/MapService.cs
  OfficeMapApi/MapService/Startup.cs
Labels: backend
